name: Staging Deployment

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Dummy build
        run: echo "Deploying to Staging environment..."
